### ISSUE TITLE
BadRequest: Invalid or duplicate property id errors for all Plone requests

### ISSUE THREAD

**Issue by davidjb** [collective/Products.AutoUserMakerPASPlugin#7]
I'm getting errors for all requests being sent to Plone objects upon upgrading from v1.x to v2.0 for me on Plone 4.3.7:

```
2016-01-21 17:54:55 ERROR Zope.SiteErrorLog
Traceback (innermost last):
  Module ZPublisher.Publish, line 127, in publish
  Module ZPublisher.BaseRequest, line 607, in traverse
  Module Products.PluggableAuthService.PluggableAuthService, line 244, in validate
  Module Products.PluggableAuthService.PluggableAuthService, line 605, in _extractUserIds
  Module Products.AutoUserMakerPASPlugin.auth, line 515, in extractCredentials
  Module Products.AutoUserMakerPASPlugin.auth, line 368, in getConfig
  Module OFS.PropertyManager, line 285, in manage_addProperty
  Module OFS.PropertyManager, line 184, in _setProperty
BadRequest: Invalid or duplicate property id
```

[This](https://github.com/collective/Products.AutoUserMakerPASPlugin/blame/master/Products/AutoUserMakerPASPlugin/auth.py#L366) is where the issue is occurring.  The properties are attributes on the AutoUserMakerPASPlugin object (eg `hasattr(self, prop[0])` return true), but `self.propertyIds()` returns only `['prefix']`, so the code attempts to add the property anyway.

I'm not familiar with the Zope internals here beyond reading the PropertyManager.py (https://github.com/zopefoundation/Zope/blob/master/src/OFS/PropertyManager.py) -- which seems to put all properties into `self._properties` and also as object attributes.  In my case, my existing plugin has the latter but not the former.

@tomgross, would this pull request in #8 be suitable as a fix?

**Comment by tomgross** [comment]
Fixed with 8b1df1c0432ae94c65fe8cb43d61b36320cb610d
